version: "3.8"

services:
  bonexapi:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env

    develop:
      watch:
        - path: .
          target: /app
          action: sync

    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
